# Generated by Django 5.0 on 2023-12-06 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('run', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('cargos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cargos')),
                ('departamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.departamentos')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.genero')),
            ],
        ),
        migrations.CreateModel(
            name='ContactosEmergencia',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.datospersonales')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parentesco')),
            ],
        ),
        migrations.CreateModel(
            name='CargasFamiliares',
            fields=[
                ('id_cargas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('run', models.CharField(max_length=10, unique=True)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.datospersonales')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.genero')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parentesco')),
            ],
        ),
    ]
